### ISSUE TITLE
Add new CLI commands to manage the runtime configuration

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#100]
The goal of this task is to add one (or many ?) commands to manage the runtime configuration (with the `@nodesecure/rc` package).

For me, the main idea is to make sure the configuration file exist somewhere in a global scope (probably in the os temporary directy ?). And then expose a command like `nsecure config` to edit the file in an editor like VSCode.

Maybe can we take inspiration on `npm config` (seems a bit complicated for a first version).

When searching/loading configuration we could search the global area and then the local with `process.cwd()`.

**Comment by tony-go** [comment]
Really good idea ^^

**Comment by Kawacrepe** [comment]
I'm gonna look into it
