### ISSUE TITLE
Add a warning when NODE_SECURE_TOKEN is missing

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#108]
It could be cool to add a warning in the CLI when the env `NODE_SECURE_TOKEN` is missing. Because without this env NPM has a pretty low ratelimit (so you can rapidly get errors).

The information is documented here: https://github.com/NodeSecure/cli#private-packages--registry

**Comment by tekeuange23** [comment]
Okay, I'll try to add a PR in the next few hours.

**Comment by fraxken** [comment]
@all-contributorsrc please add @tekeuange23 for code

**Comment by fraxken** [comment]
@all-contributors please add @tekeuange23 for code
