### ISSUE TITLE
Implement OpenSSF scorecard

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#118]
The idea is to implement the [scorecard](https://github.com/ossf/scorecard) by the Open Source Security Foundation (OpenSSF).

We can take inspiration on the tool [deps.dev](https://deps.dev/) who already have an implementation:
![image](https://user-images.githubusercontent.com/4438263/189178902-38228354-3782-408d-9f6c-8462d143049b.png)

Those data are available online and fetchable by [REST API](https://api.securityscorecards.dev/). I think we should implement this like Bundlephobia API (by exposing an API on the HTTP Server to avoid cross domain issues).

The question that remains is where in the interface should we place this information?

**Comment by tekeuange23** [comment]
Well received.

**Comment by tekeuange23** [comment]
I mean if I get it well, I'd enhance an existing Http RestApi with endpoinds and models as shown the doc [OpenSSF Api Documentation](https://api.securityscorecards.dev/)

**Comment by fraxken** [comment]
We now have a back-end SDK to consume the OpenSSF API: https://github.com/NodeSecure/ossf-scorecard-sdk. So the overall idea is to:

1. Add an API on the CLI http server and use the SDK to fetch the Scorecard result.
2. Add UI in the left menu (and load data on the http server when we select a package).

For the UI my idea is to add a little menu/info where I draw a red line:
![image](https://user-images.githubusercontent.com/4438263/200122667-30407d63-5de3-4e6b-afb8-efb1928b1057.png)

We can move step by step with a first version that only show the score. Then later we can code the complete UI to show all checks details (like deps.dev).
