### ISSUE TITLE
OpenSSF scorecard CLI command

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#133]
Add a new command to show OpenSSF scorecard result on the CLI

```
$ nsecure scorecard [package]
```

If the options `package` is missing then we are retrieving the git repository at the current working dir (there is maybe a subject on how to fetch the required git metadata, probably by reading `.git/config` file).

Most of the work for this task is about building the stdout with good colors and formats.

Example on how to fetch scorecard result with the OpenSSF SDK: https://github.com/NodeSecure/cli/blob/master/src/http-server/endpoints/ossf-scorecard.js#L9

**Comment by PierreDemailly** [comment]
I'm on it
