### ISSUE TITLE
Add NodeSecure favicon

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/cli#134]
Currently we use Node.js favicon: https://raw.githubusercontent.com/NodeSecure/cli/master/public/favicon.ico
It would be nice to replace it with our own logo: https://avatars.githubusercontent.com/u/85318671?s=200&v=4

**Comment by Ineslujan** [comment]
Hello, can I manage this issue ?

**Comment by PierreDemailly** [comment]
Hi @Ineslujan, yeah sure :)

**Comment by Nababratadeb-NITA** [comment]
Hey @PierreDemailly is this issue solved? or I can do this?

**Comment by Ineslujan** [comment]
Hello @PierreDemailly, I did the pull request here : "change the node.js favicon by our own logo #137"
Thank you
