### ISSUE TITLE
Settings should be applied on save

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/cli#221]
When we change the settings i.e. disabling a SAST warning, we need to refresh the page to have the new settings applied.

The idea is to refresh the nodes on save to make the the settings applied without the need to reload the page.

**Comment by bilalshaikh292** [comment]
Heyy is the issue Still open I would like to contribute ?

**Comment by PierreDemailly** [comment]
@bilalshaikh292 Sure, don't hesitate if you need any guidance ;)
