### ISSUE TITLE
Add external link to visualiser for Scorecard

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#233]
The goal of the task is to add an external link to [the following scorecard visualiser](https://github.com/KoolTheba/openssf-scorecard-api-visualizer#how-to-use-it) in the **Security Scorecard** tab.

`https://kooltheba.github.io/openssf-scorecard-api-visualizer//projects/${platform}/${org}/${repo}`

![image](https://github.com/NodeSecure/cli/assets/4438263/13fba8a1-9dae-4815-af6c-e7812f906f68)

Maybe under the score ?

**Comment by PierreDemailly** [comment]
I would see it as a footer or above the score. It looks harder to have a smooth result with the link under the score but why not?
Maybe try adding the link at multiple places to see where it fills better
