### ISSUE TITLE
Highlight suspicious script

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#257]
Could be cool to highlight suspicious script in the UI (so we do not miss them).

For example here install should be highlighted (maybe we could also add a little warning sign?).
![image](https://github.com/NodeSecure/cli/assets/4438263/7af8278e-8a43-4fe7-81bf-eb6b147837f0)

Reproducible example with  sharp@0.31.3 and NPM Audit as Vulnerability strategy (this is the default if you don't touch it).

To remind you, unsafe script are:
```js
const kUnsafeNpmScripts = new Set([
  "install",
  "preinstall",
  "postinstall",
  "preuninstall",
  "postuninstall"
]);
```

**Comment by lchauha** [comment]
@fraxken I would like to work on this issue. Please assign
