### ISSUE TITLE
Improve i18n support

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#310]
There is still a lot of room to improve the i18n support across the Web UI:

- Moving i18n package translation locally here (**cli** and **ui**).
- Find a way to support i18n in front-end JavaScript assets (see expandable component)

Other components impacted in the top of my mind:
- home/overview (a lot of text injected from code)
- network (for edges labels)
- locker

I think the goal is to successfully tokenize everything.

**Comment by PierreDemailly** [comment]
![image](https://github.com/NodeSecure/cli/assets/39910767/fde5d8ac-035f-4e7d-a225-2a37c06a95ce)
CLI also needs i18n improvements, missing i18n for `config` & `config create`

Note that we cannot translate sade -> https://github.com/lukeed/sade/blob/8aa4a69e95fbfba88cf49082713900ecbe27f183/src/utils.js#L67
Maybe its an opportunity to build our own package in TopCli 👀
