### ISSUE TITLE
Allow to customize the theme for report export

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#352]
When exporting a report (home > generate report) it could be cool to be able to select the theme by adding a new checkbox or something like that (light by default or dark).

You need to provide the data to the API and update the http endpoint here: https://github.com/NodeSecure/cli/blob/master/src/http-server/endpoints/report.js

**Comment by ankiiisharma** [comment]
hey @fraxken , can you please elaborate this more?

**Comment by fraxken** [comment]
@ankiiisharma The report (https://github.com/NodeSecure/report) project we use to generate the report can take a light or dark theme.

Current static config use the light one by default
https://github.com/NodeSecure/cli/blob/537e9987f4b3dc2c8ae7782cc8808c618dce1a41/src/http-server/endpoints/report.js#L14

In the Web UI we want to add an option to choose between light or dark theme
![image](https://github.com/NodeSecure/cli/assets/4438263/a999942d-5d0e-4e42-858c-27d20bb9caaf)

This popup is generated when you click "generate report" in the home view
![image](https://github.com/NodeSecure/cli/assets/4438263/5186b346-187e-4788-bf10-3df2b4c4645e)

**Comment by ankiiisharma** [comment]
@fraxken so you want a toggle there so that user can switch their theme. Am i right?

**Comment by fraxken** [comment]
Yes (since we only have two right now no need to go with something complicated). A boolean is enough.
