### ISSUE TITLE
Better screenshot or product demo video

### ISSUE THREAD

**Issue by conartist6** [NodeSecure/cli#394]
The screenshot on the repo homepage is a low resolution so that the details of what the UI looks like are just a bit too blurry to be able to see what you're looking at. I think perhaps if you scaled the window down before you took the screenshot it wouldn't get downsized so much as to make the text illegible?

Might be worth fixing though since it isn't another low-friction way to see the product in action

**Comment by fraxken** [comment]
@conartist6 Yes, we discussed that months ago with @PierreDemailly but hadn't taken the time to do it until now.

**Comment by conartist6** [comment]
Sweet, thanks!
