### ISSUE TITLE
Document all commands

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#411]
The current documentation is quite incomplete, and many commands of the tool, such as the **report** command, are not documented.

My idea is to keep the usage example section, but instead of including numerous tables, we could create separate documentation for each command (in a folder `/docs/cli/`  for example).

All commands are defined here: https://github.com/NodeSecure/cli/blob/master/bin/index.js

---

A bit like [jsonschema CLI README](https://github.com/Intelligence-AI/jsonschema?tab=readme-ov-file#usage):
![image](https://github.com/user-attachments/assets/4010152a-7d09-4a22-8c45-d76590583e2e)

---

![image](https://github.com/user-attachments/assets/d71b31f3-56a0-4ef5-91a0-08f9c75c577e)

**Comment by Code-Hacker26** [comment]
Hey , I am interested  in contributing  to  this issue , 
It wouls be great if You can thow some more light to it

**Comment by fraxken** [comment]
@Code-Hacker26 Someone is already working on it (he just didn't comment here to take ownership)
