### ISSUE TITLE
Amélioration de la documentation des commandes CLI

### ISSUE THREAD

**Issue by foucsi** [NodeSecure/cli#412]
Something like this ?
<img width="1380" alt="Capture d’écran 2024-08-10 à 15 07 58" src="https://github.com/user-attachments/assets/6cfce63d-7e0f-4a0c-b0c8-90ed60d6d0c7">

**Comment by fraxken** [comment]
@foucsi Yes, but we don't need the `overview.md` file; its content should be included in the README.md after the usage example.

And please do not open new issue (use #411)
